name: SSH VM

on:
  workflow_dispatch:

jobs:
  vm:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Start SSH session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true

      - name: Keep VM alive
        run: sleep 21600
